package seeder

import "github.com/wafellofazztrack/lectronic-backend/database/orm/model"

var ProductSeed = model.Products{
	{
		Name:        "iPhone 13 Pro Max",
		Description: "The iPhone 13 Pro Max features a triple camera system, A15 Bionic chip, and 5G connectivity.Eu dolor dolor elit qui occaecat reprehenderit sunt ullamco enim cillum Lorem officia cillum non.Mollit id aliquip irure culpa tempor irure do.Nisi velit officia sunt ea.Dolore consectetur labore amet reprehenderit commodo aliquip dolor sint cillum irure nostrud duis deserunt consequat.Aute ad enim cillum mollit consequat est excepteur labore ipsum cupidatat ut ad ipsum id.Amet voluptate sint nisi irure in ipsum fugiat cillum mollit aute.Est id nostrud fugiat in Lorem irure fugiat ad amet ipsum aliquip.Officia culpa dolor id exercitation excepteur aliquip duis qui do anim dolor.",
		Price:       23499000,
		Category:    "Phone",
		Image:       "1.jpg",
		Stock:       12,
	},
	{
		Name:        "Samsung Galaxy S21 Ultra",
		Description: "The Samsung Galaxy S21 Ultra features a 108MP camera, 8K video recording, and an Exynos 2100 chip.Nisi fugiat excepteur Lorem occaecat veniam eu ea mollit nostrud culpa laborum reprehenderit velit magna.Id veniam labore velit labore anim.Dolore minim eiusmod amet laboris magna aliqua amet deserunt ut enim qui exercitation.Ad deserunt sit aliqua fugiat aliquip officia deserunt incididunt commodo enim fugiat sit.Nisi voluptate ullamco consequat sunt mollit adipisicing fugiat aute laborum anim voluptate proident.Non tempor labore qui veniam nostrud aliqua fugiat pariatur in laboris excepteur aliquip incididunt.",
		Price:       18999000,
		Category:    "Phone",
		Image:       "2.jpg",
		Stock:       8,
	},
	{
		Name:        "Google Pixel 6 Pro",
		Description: "The Google Pixel 6 Pro features a 6.7-inch QHD+ OLED display, 50MP camera, and Google Tensor processor.Excepteur consectetur quis anim dolor aute ex aliquip fugiat consequat tempor ea.Nulla exercitation dolore reprehenderit ex pariatur ea.Magna commodo adipisicing laborum cupidatat exercitation.Sunt eu consequat duis irure.Enim aute qui pariatur in do amet aliquip ea ullamco fugiat ullamco cupidatat incididunt.Adipisicing culpa velit aute exercitation consectetur irure ea.Est ut proident officia Lorem.Irure est voluptate dolor adipisicing.Amet magna aliqua laborum id duis irure laborum et officia duis adipisicing.Pariatur elit dolore consectetur Lorem nostrud mollit labore sit mollit.Aliqua exercitation aliquip est proident fugiat sint veniam est consectetur ex sint ut occaecat.",
		Price:       14999000,
		Category:    "Phone",
		Image:       "3.jpg",
		Stock:       18,
	},
	{
		Name:        "MacBook Air M1",
		Description: "The MacBook Air M1 features Apple's M1 chip, 8-core GPU, and up to 18 hours of battery life.Veniam amet laboris aliqua enim ad consectetur eu Lorem sint.Qui ullamco incididunt enim sint elit in labore eiusmod Lorem Lorem.Anim eiusmod pariatur ad non.Enim ullamco fugiat amet incididunt incididunt labore dolore quis.Cillum proident qui ipsum esse fugiat et ullamco nisi fugiat officia qui.Exercitation do ex ullamco sint veniam quis.Non velit voluptate aute in excepteur pariatur quis eiusmod est dolor sint consequat laborum duis.Sunt esse quis qui anim labore occaecat sint ut.Mollit cupidatat pariatur incididunt est ullamco aute fugiat duis proident est reprehenderit fugiat proident.Minim tempor ex labore mollit magna aliquip.Minim sunt duis occaecat laboris mollit in nulla cillum dolore dolor minim velit.Cupidatat consequat mollit elit duis minim et nostrud ea fugiat in sint ullamco labore.Commodo exercitation adipisicing cupidatat consectetur.Tempor officia mollit aliquip consectetur in dolore minim Lorem pariatur fugiat.Ut velit consectetur deserunt dolore sit enim anim ut et.Aute ex qui aliqua commodo labore id officia do deserunt quis sint culpa cillum occaecat.Dolore nisi ullamco sit reprehenderit adipisicing irure ad cupidatat amet nisi qui.Veniam duis officia reprehenderit fugiat anim excepteur.Aliquip anim minim sint irure ad culpa ut reprehenderit esse dolore nulla mollit.",
		Price:       16999000,
		Category:    "Laptop",
		Image:       "4.jpg",
		Stock:       6,
	},
	{
		Name:        "Dell XPS 13",
		Description: "The Dell XPS 13 features an 11th Gen Intel Core i7 processor, InfinityEdge display, and up to 19 hours of battery life.Lorem officia Lorem reprehenderit enim do irure consequat esse deserunt in.Aute magna aliquip ea tempor commodo.Sint proident officia magna ut cupidatat elit esse enim.Est enim anim occaecat consectetur id proident.Commodo aliqua veniam occaecat tempor ipsum anim magna proident dolore exercitation nulla exercitation pariatur.Occaecat enim nulla sunt nisi dolore adipisicing tempor eu incididunt non eiusmod.Esse irure non enim ut.Dolore dolor nisi elit duis amet voluptate adipisicing ex nisi cupidatat nostrud.Velit pariatur aute consectetur minim ad fugiat eu.Ullamco esse eiusmod sunt labore enim nisi nostrud voluptate irure eu adipisicing nulla ipsum exercitation.Do fugiat labore et pariatur irure laboris sit aute irure aliqua occaecat.Reprehenderit ea pariatur do voluptate sit elit deserunt qui duis dolor qui voluptate voluptate.Labore ex reprehenderit irure consequat mollit in veniam Lorem fugiat sit et.Mollit velit sint fugiat sint incididunt.Laborum id cillum labore ea ea do est aliqua nulla amet.Aute officia elit occaecat mollit cillum laboris tempor laboris deserunt. Ut est laboris sint exercitation magna amet aliquip excepteur exercitation ipsum aute nisi veniam.Ipsum sunt magna commodo velit proident dolore excepteur excepteur id ut enim ipsum.Proident irure qui nostrud deserunt.Commodo enim culpa qui duis consequat anim pariatur eu quis est tempor.Anim irure ut commodo Lorem dolore fugiat quis sint irure anim occaecat Lorem.Minim cupidatat duis duis sint minim in ipsum.Pariatur tempor sit est fugiat.Eiusmod cupidatat incididunt nostrud laboris occaecat cupidatat.Quis esse minim sunt amet minim ea ut sit qui excepteur sunt esse.Lorem cupidatat esse officia occaecat deserunt id labore aute.Adipisicing ad aliqua officia commodo anim consequat eu labore mollit dolor ullamco consequat pariatur veniam.Culpa nostrud consequat nostrud deserunt non velit pariatur.Anim excepteur velit veniam dolor amet sint labore ea nostrud ipsum cupidatat.Est commodo tempor velit culpa aliqua sit adipisicing aliquip.Ullamco do mollit anim dolore enim laborum eu occaecat enim nulla occaecat dolor proident irure.Consectetur eiusmod irure est est qui laboris duis occaecat excepteur deserunt consequat ad ex eiusmod.Ea occaecat eiusmod ad occaecat anim qui magna commodo laborum nulla.Irure irure minim quis tempor eiusmod occaecat.Reprehenderit sint non excepteur nostrud.Ad sunt excepteur incididunt veniam in laborum reprehenderit cillum ipsum.Non aliquip eu consectetur officia do.Veniam qui ipsum dolore aliqua labore fugiat reprehenderit sunt non proident ipsum est aliquip commodo.Sunt irure aliqua cillum incididunt ipsum nostrud voluptate nisi est aliquip proident sit.",
		Price:       19999000,
		Category:    "Laptop",
		Image:       "5.jpg",
		Stock:       10,
	},
	{
		Name:        "Asus ROG Zephyrus G14",
		Description: "The Asus ROG Zephyrus G14 features an AMD Ryzen 9 processor, Nvidia GeForce RTX 3060 GPU, and 1440p display.Ex mollit reprehenderit exercitation non laborum anim eiusmod.Sit nisi eiusmod minim commodo cillum sint cupidatat.Sit et incididunt irure nulla dolore esse.Proident nisi esse dolor esse aliqua pariatur consectetur aliqua ea labore et ea sit in.Aliquip aliqua irure pariatur sunt commodo deserunt voluptate excepteur deserunt culpa aliqua ad magna.Aliquip enim cillum Lorem qui velit aliquip.Dolor nostrud proident aute ullamco ea enim.Sunt incididunt consectetur eu fugiat deserunt esse.Duis fugiat ex eiusmod aliquip id ut eu reprehenderit et ullamco.Qui esse ipsum aliqua laborum dolore sint quis anim.Culpa velit eiusmod ullamco id elit eu id labore nostrud irure tempor occaecat eu.Nisi fugiat excepteur excepteur id.Non mollit voluptate aliquip veniam aute voluptate quis ex do Lorem.Eiusmod commodo enim ad duis nisi velit voluptate irure labore.Nostrud incididunt tempor eiusmod do ut est.Nisi consectetur labore enim ut consectetur commodo aliquip Lorem eiusmod occaecat labore.Fugiat consectetur elit ad est duis.Esse qui dolore incididunt velit voluptate duis consequat tempor occaecat mollit anim officia.Enim consequat voluptate magna tempor velit pariatur consequat laborum et.Occaecat est eu Lorem labore est exercitation sint duis enim ipsum esse.Id labore pariatur anim labore sint nisi.Deserunt enim sunt in consequat proident aliquip velit.Tempor labore nisi eu pariatur sit ex qui laborum consectetur quis adipisicing voluptate culpa non.Occaecat irure officia esse in duis commodo non.Irure reprehenderit qui occaecat ut consectetur.Minim velit ut eu dolore.Est ullamco aute id proident adipisicing minim duis deserunt.Occaecat veniam velit nostrud reprehenderit excepteur reprehenderit voluptate commodo aute commodo culpa veniam qui elit.Incididunt Lorem nisi quis occaecat aute aliquip veniam anim velit occaecat duis duis elit.Minim mollit in irure ex labore in tempor est dolor cupidatat sint eu do.Ut veniam pariatur exercitation aliquip officia pariatur aliquip laborum cillum ullamco laboris sit exercitation Lorem.Nostrud consectetur officia in cupidatat dolore nostrud consectetur sit id cillum minim quis reprehenderit.Fugiat voluptate id ipsum aliqua fugiat incididunt mollit.Ullamco magna nostrud ut eiusmod quis magna proident excepteur proident cillum reprehenderit.In eu Lorem deserunt eiusmod.",
		Price:       25999000,
		Category:    "Laptop",
		Image:       "6.jpg",
		Stock:       4,
	},
	{
		Name:        "Bose QuietComfort 35 II",
		Description: "The Bose QuietComfort 35 II features noise-cancellation technology, up to 20 hours of battery life, and Alexa voice control. Aliqua anim id veniam aute do culpa.Sunt occaecat excepteur dolor ea do ullamco.Aute cupidatat eu magna deserunt incididunt do incididunt dolore labore qui commodo aliqua officia eiusmod.Exercitation incididunt aliquip dolore laborum occaecat nostrud mollit laboris non consectetur dolor veniam.Et anim ut ea pariatur officia pariatur adipisicing eu.Ipsum id aliqua veniam laboris consectetur exercitation magna amet mollit reprehenderit velit amet.Officia Lorem labore sit nulla mollit nisi enim non culpa velit.Id et nostrud pariatur mollit ipsum et.Ipsum ipsum ipsum ipsum deserunt irure non adipisicing qui sint enim commodo nisi sit labore.Adipisicing ad velit minim commodo adipisicing amet Lorem mollit esse.Proident do nostrud cupidatat anim incididunt.Ipsum occaecat adipisicing anim velit.Pariatur do in non ad velit anim adipisicing ea nulla.Do consectetur esse proident exercitation adipisicing laborum Lorem dolore velit cupidatat in ea aute.Id aliquip ad excepteur proident labore minim ipsum adipisicing.Consequat do adipisicing proident sit mollit.Non fugiat sunt laboris Lorem sit exercitation consequat ex Lorem ut.Commodo officia sit ad consequat deserunt ut sit.Ullamco eiusmod cillum dolore excepteur quis id ea aliqua ut est exercitation cupidatat elit aliquip.Amet voluptate exercitation reprehenderit occaecat aute Lorem.",
		Price:       3499000,
		Category:    "Headphone",
		Image:       "7.jpg",
		Stock:       15,
	},
	{
		Name:        "Sony WH-1000XM4",
		Description: "The Sony WH-1000XM4 features noise-cancellation technology, 30 hours of battery life, and support for LDAC audio.Amet sit occaecat velit adipisicing sit eu tempor officia laborum fugiat dolor.Non sit Lorem commodo veniam do sunt labore consequat ipsum officia pariatur sunt culpa.Nostrud do deserunt velit sit est deserunt aute.Sint sunt laborum ex esse eu.Amet nostrud sit sit magna sint ullamco nostrud.Anim deserunt occaecat ipsum consectetur veniam aliqua do laborum velit exercitation.Nostrud irure irure est quis tempor culpa officia deserunt.Ex proident deserunt commodo adipisicing esse pariatur nisi laboris.Nostrud id est culpa ipsum sint deserunt ex dolore.Velit officia sint consectetur consequat quis qui.Ipsum incididunt incididunt et amet voluptate laboris sint eiusmod velit nostrud ullamco.Nostrud eiusmod elit commodo adipisicing.Veniam culpa dolor nulla consequat commodo nulla ex eu labore Lorem qui.Adipisicing proident fugiat voluptate eiusmod amet occaecat et pariatur officia.Irure exercitation excepteur labore eu dolor ex qui sint.Mollit ex officia et culpa consectetur Lorem ut pariatur dolore ad adipisicing do.Aliquip amet aute proident consectetur et eu minim est quis nulla.",
		Price:       4299000,
		Category:    "Headphone",
		Image:       "8.jpg",
		Stock:       9,
	},
	{
		Name:        "Jabra Elite 85t",
		Description: "The Jabra Elite 85t features active noise-cancellation, up to 25 hours of battery life, and customizable equalizer settings.Elit mollit cupidatat adipisicing excepteur velit minim pariatur et.Nostrud in ipsum incididunt nisi ut minim est velit irure fugiat quis.Ullamco velit consequat sint cupidatat dolore aliquip excepteur nisi.Minim amet sunt aliquip et est ea eiusmod reprehenderit ullamco.Sunt labore enim dolore amet tempor esse.Do velit ullamco eiusmod tempor ullamco sint.Aliqua ex veniam irure sint adipisicing aute exercitation est est proident veniam.Quis id quis nulla dolore.Laborum nostrud ex non nulla est elit quis ut sunt quis do ad.Nulla incididunt proident ex proident pariatur non dolore ullamco ipsum Lorem. Pariatur aliquip sit elit minim cupidatat magna officia.Dolor pariatur magna id do.Consequat aliqua consequat officia eiusmod anim est minim pariatur magna ad.Excepteur ut aute ipsum culpa sit laborum cupidatat cillum esse.Quis qui dolore nulla laborum.Nulla ea Lorem laboris ea exercitation irure commodo sit elit irure amet laborum velit.Ea id adipisicing ad Lorem ex in exercitation commodo nulla dolor consequat aute enim labore.Qui proident minim occaecat deserunt amet id ex minim voluptate qui.Eiusmod deserunt exercitation esse Lorem do.Ea nisi minim fugiat consectetur ut fugiat voluptate.Culpa irure cupidatat dolore cillum.Laboris nulla irure minim reprehenderit Lorem deserunt.Proident cupidatat non elit cupidatat officia dolor nulla officia culpa fugiat nulla.",
		Price:       2999000,
		Category:    "Headphone",
		Image:       "9.jpg",
		Stock:       12,
	},
	{
		Name:        "OnePlus 10 Pro",
		Description: "The OnePlus 10 Pro features a 120Hz QHD+ display, 50MP camera, and Snapdragon 8 Gen 1 processor.Incididunt magna id minim minim do eiusmod.Ex Lorem ex ad est do.Sunt sit quis occaecat tempor elit pariatur et consectetur occaecat exercitation.Non proident deserunt veniam adipisicing duis qui nostrud consequat tempor.Pariatur commodo cupidatat eiusmod aliquip est tempor minim labore ex.Occaecat veniam commodo consectetur adipisicing fugiat qui reprehenderit culpa non dolor labore eu.In ea laboris eu anim sunt consequat culpa.Voluptate id quis aute exercitation consequat amet.Id laboris dolore ex deserunt consequat ipsum consectetur consequat.Qui mollit Lorem et ullamco ipsum nisi incididunt aliquip nostrud.Magna quis qui adipisicing ad proident.Esse aute qui veniam laboris.Fugiat duis deserunt ipsum excepteur consectetur.Nisi amet ex incididunt velit quis qui proident.Cillum aliquip ad magna in adipisicing qui.Deserunt est dolor laborum id irure deserunt irure.Minim irure enim duis amet aliquip sunt.Esse minim adipisicing voluptate do id eiusmod ex ad aute culpa deserunt.",
		Price:       13999000,
		Category:    "Phone",
		Image:       "10.jpg",
		Stock:       7,
	},
	{
		Name:        "Xiaomi Mi 11",
		Description: "The Xiaomi Mi 11 features a 6.81-inch AMOLED display, 108MP camera, and Snapdragon 888 processor.Tempor pariatur exercitation proident irure duis excepteur velit mollit voluptate culpa.Consequat aliquip elit sunt aliqua.Duis minim sint sint tempor enim.Elit est mollit Lorem elit anim quis sunt aute dolor occaecat ullamco labore qui id.Fugiat enim duis id ad ex.Voluptate velit esse sunt sit ut aute laborum.Esse deserunt voluptate qui laboris adipisicing esse sit consequat irure excepteur.Id magna incididunt proident ad pariatur occaecat consectetur laborum labore nulla ut ullamco.Dolor cupidatat anim laborum quis do laborum laborum ex minim ipsum tempor ut.Labore non qui quis consequat nulla magna commodo labore.Non deserunt velit pariatur qui aliqua laboris.Sunt cupidatat nostrud ea aute dolore.Ad anim ea Lorem laboris.Velit eu elit adipisicing labore anim dolor laboris mollit eu laborum dolore voluptate incididunt.Qui mollit minim qui cupidatat occaecat exercitation laboris nisi est eu.Tempor consequat Lorem laborum labore culpa occaecat in est mollit id sunt id.Occaecat id eu ea occaecat deserunt cupidatat.Culpa in eiusmod aliquip dolor incididunt sint.Consequat fugiat dolore pariatur ut deserunt nostrud mollit quis velit nisi enim anim aute.",
		Price:       9999000,
		Category:    "Phone",
		Image:       "11.jpg",
		Stock:       14,
	},
	{
		Name:        "Realme GT Master Edition",
		Description: "The Realme GT Master Edition features a 6.43-inch Super AMOLED display, 64MP camera, and Snapdragon 778G processor.Fugiat enim laborum dolor voluptate ipsum pariatur laborum Lorem occaecat exercitation elit esse laboris velit.Proident dolor velit sit pariatur ea quis dolor.Deserunt sit proident duis exercitation proident mollit sunt ea nostrud esse reprehenderit dolore.Sit commodo ea ad ex laboris.Ad dolore veniam amet nulla.Magna nulla anim ad cupidatat deserunt.Pariatur consequat laborum magna sunt labore.Elit mollit aute commodo irure anim in.Anim amet consequat labore mollit deserunt ad enim amet dolor magna ullamco tempor duis.Duis esse cillum minim id dolor voluptate reprehenderit ullamco ut sit velit elit fugiat.Reprehenderit fugiat dolore ex irure Lorem fugiat nostrud fugiat culpa deserunt voluptate eu sint.Reprehenderit commodo minim velit occaecat labore in.Et officia mollit consequat fugiat proident amet velit.Et laborum elit est exercitation esse ullamco consectetur sit Lorem ut consequat nisi.Elit mollit labore exercitation esse veniam dolor magna deserunt consectetur.Non dolore exercitation laborum voluptate elit dolor Lorem pariatur ex ut Lorem.Culpa anim veniam elit do ad duis elit Lorem ut eiusmod quis incididunt incididunt in.Fugiat tempor consectetur culpa consectetur velit magna duis non Lorem qui et deserunt minim.Cillum nostrud pariatur dolor anim voluptate est Lorem nisi consequat.Do mollit consectetur id esse amet proident.Deserunt sit pariatur laborum sit id adipisicing.Consequat aute proident sit duis fugiat minim tempor qui qui.Pariatur non mollit velit Lorem eu aute.Mollit cupidatat nostrud adipisicing reprehenderit eu est.Aliquip non id voluptate ut exercitation reprehenderit.Minim consequat nostrud irure aliquip ut ad nostrud incididunt ullamco duis ipsum esse sunt.Minim irure nisi ea esse exercitation est elit nulla.Ex quis voluptate eu incididunt dolor aute enim qui proident proident laborum.Consectetur aute amet eu mollit fugiat laboris ea excepteur qui duis.Labore exercitation cillum nisi adipisicing labore ipsum minim dolor eiusmod cillum adipisicing nostrud reprehenderit.Ut in nulla proident mollit cillum deserunt aute labore in.Duis duis mollit duis amet magna.Incididunt minim cupidatat veniam ad consectetur deserunt fugiat ut esse laboris.Dolor sit sint commodo nisi labore culpa magna ipsum eiusmod.Dolor in officia mollit sint esse nulla.Ipsum excepteur ad duis ullamco.",
		Price:       4999000,
		Category:    "Phone",
		Image:       "12.jpg",
		Stock:       9,
	},
	{
		Name:        "HP Spectre x360",
		Description: "The HP Spectre x360 features an 11th Gen Intel Core i7 processor, 4K OLED display, and up to 14 hours of battery life.Nulla dolor magna deserunt pariatur ipsum amet in non.Ullamco esse elit elit non nisi Lorem incididunt.Sit ut reprehenderit commodo nostrud fugiat proident magna magna et ea.Reprehenderit deserunt sunt amet nostrud eu ad consequat occaecat exercitation aliqua deserunt.Aliquip ex laboris commodo aliquip qui anim eu cillum reprehenderit laborum culpa excepteur.Fugiat amet veniam laborum amet exercitation veniam enim.Consectetur irure sunt aliqua et magna.Velit consequat dolore nostrud pariatur veniam deserunt nulla anim amet nulla excepteur sit anim.Ad nulla incididunt laborum qui ex nulla eu sint nostrud.Laboris amet occaecat aliqua esse amet ex id officia occaecat Lorem.Consequat tempor sit anim tempor consectetur occaecat labore quis pariatur irure commodo irure anim.Duis do consequat mollit voluptate enim.Ad eu nisi consequat eiusmod in nostrud in in eiusmod in.Quis adipisicing nisi quis magna laborum laboris cillum do.Aliquip et aliquip pariatur ea.",
		Price:       23499000,
		Category:    "Laptop",
		Image:       "13.jpg",
		Stock:       5,
	},
	{
		Name:        "Lenovo ThinkPad X1 Carbon",
		Description: "The Lenovo ThinkPad X1 Carbon features an 11th Gen Intel Core i7 processor, 14-inch 4K display, and up to 16 hours of battery life.Anim fugiat fugiat in nisi.Occaecat cupidatat duis ipsum laborum voluptate aute consectetur qui aute proident amet.Ullamco labore reprehenderit et elit minim nisi consectetur velit Lorem.Non nulla proident tempor mollit incididunt elit ut sit eu ex Lorem minim et.Tempor est exercitation velit ipsum velit.Officia eiusmod labore officia qui culpa excepteur laboris ullamco est incididunt laboris magna sunt.Nisi anim dolore consequat occaecat reprehenderit excepteur minim incididunt sit pariatur excepteur.Officia id qui reprehenderit Lorem.Nisi esse eiusmod voluptate ea commodo.Voluptate eu elit duis adipisicing cillum labore culpa id.Duis tempor culpa aute exercitation nisi dolore sunt nisi excepteur velit.Sint exercitation cupidatat duis id cupidatat cupidatat.Aliqua proident sunt occaecat eiusmod nulla cupidatat cillum sunt sit duis officia qui.Est pariatur nisi mollit dolor ex.Sint ipsum irure commodo exercitation et laboris magna velit ipsum excepteur nulla.Aute cupidatat in eiusmod eiusmod est voluptate labore est.Anim labore irure sunt officia pariatur consectetur sunt.Nisi voluptate tempor Lorem aute velit do ea minim incididunt officia ad enim.",
		Price:       18999000,
		Category:    "Laptop",
		Image:       "14.jpg",
		Stock:       11,
	},
	{
		Name:        "Acer Swift 5",
		Description: "The Acer Swift 5 features an 11th Gen Intel Core i7 processor, 14-inch 1080p display, and up to 17 hours of battery life.Enim dolor commodo amet culpa id.Incididunt pariatur tempor magna cupidatat duis tempor incididunt eiusmod ipsum.Enim laborum aute pariatur tempor ipsum fugiat voluptate non.Qui Lorem nostrud Lorem do do enim adipisicing.Cupidatat ex duis incididunt occaecat cillum qui.Id ipsum nulla excepteur quis dolor tempor esse sint esse consectetur duis excepteur fugiat dolore.Incididunt ullamco officia voluptate reprehenderit magna sint eiusmod sit laboris ullamco laboris aliqua occaecat.Mollit culpa anim et consequat fugiat duis.Mollit culpa id aute laborum dolore occaecat.Mollit veniam excepteur minim amet dolore.Occaecat ex dolor enim est elit ullamco duis cillum amet magna ea est sit.Tempor laborum nostrud elit Lorem et enim aliqua cupidatat labore.Ex dolor sint voluptate enim consectetur dolore do irure voluptate consequat.Ut culpa incididunt duis est sint quis ad sunt ut dolor mollit laborum velit ullamco.",
		Price:       9999000,
		Category:    "Laptop",
		Image:       "15.jpg",
		Stock:       8,
	},
	{
		Name:        "Beyerdynamic DT 990 Pro",
		Description: "The Beyerdynamic DT 990 Pro features open-back design, 250 ohm impedance, and a frequency response of 5 Hz - 35 kHz.Dolor in aute Lorem velit eu.Minim id consequat quis qui consectetur aliqua deserunt tempor consequat nostrud labore nisi.Magna ut aliqua labore in nulla.Aute nisi labore aliquip dolor.Deserunt et ea aliqua labore cillum ullamco non veniam occaecat nisi.Ut proident cillum nostrud velit sunt culpa culpa magna aute commodo cupidatat elit.Commodo tempor exercitation in nostrud est occaecat et fugiat consectetur sunt.Sit laborum velit irure deserunt ipsum in anim velit esse esse ea.Excepteur reprehenderit aute consectetur mollit do consequat ea nisi nulla deserunt adipisicing pariatur.Commodo in nisi elit ullamco pariatur adipisicing enim adipisicing sunt ut fugiat non aute eu.Deserunt occaecat laborum occaecat fugiat qui proident quis adipisicing proident nisi consectetur laboris.Anim officia officia ea laborum consectetur fugiat fugiat.Dolore consectetur adipisicing eiusmod voluptate.Nostrud ipsum sunt ipsum irure irure incididunt sunt nisi laboris.Aliqua sit sunt aliqua et adipisicing ut dolor culpa irure irure duis.",
		Price:       3699000,
		Category:    "Headphone",
		Image:       "16.jpg",
		Stock:       6,
	},
	{
		Name:        "Sennheiser HD 660 S",
		Description: "The Sennheiser HD 660 S features open-back design, 150 ohm impedance, and a frequency response of 10 Hz - 41 kHz.Mollit labore ad aute dolore est nisi in.Labore amet laborum ex ex incididunt sunt cupidatat adipisicing minim ad cillum exercitation.Consectetur eiusmod ipsum laborum anim cillum nulla labore cupidatat velit pariatur.Eu est reprehenderit ut dolor nostrud enim consequat esse.Eiusmod fugiat nulla officia magna.Anim in velit sunt consectetur cupidatat aliquip exercitation anim irure nostrud.Qui id exercitation consectetur nisi nisi.Aliqua ex cillum ea reprehenderit tempor duis sunt fugiat.Amet quis nulla sint et aute magna velit nulla.Excepteur est mollit deserunt cupidatat quis.In ipsum non non irure tempor aliquip qui id ex Lorem adipisicing.Ea ipsum tempor nulla deserunt exercitation nostrud excepteur exercitation.Sint sunt elit labore fugiat non fugiat nostrud adipisicing consectetur proident consequat.Laboris cupidatat quis anim mollit qui.Aliquip officia aliqua ex laborum deserunt nisi commodo sit ipsum ea.",
		Price:       7899000,
		Category:    "Headphone",
		Image:       "17.jpg",
		Stock:       3,
	},
	{
		Name:        "Audio-Technica ATH-M50x",
		Description: "The Audio-Technica ATH-M50x features closed-back design, 45mm drivers, and a frequency response of 15 Hz - 28 kHz.Laboris irure occaecat dolor sint consequat.Fugiat sit ex aliquip irure aliquip ut sint cillum qui amet fugiat.Id magna exercitation reprehenderit aute exercitation adipisicing duis.Voluptate officia incididunt voluptate do cupidatat.Tempor sunt dolore sint ipsum dolor laborum ullamco esse tempor aute minim.Deserunt excepteur magna laboris veniam in quis.Cupidatat consequat elit anim voluptate deserunt consequat sunt.Reprehenderit ullamco consectetur exercitation voluptate ex pariatur esse in fugiat ea anim aute.Sint duis cupidatat adipisicing excepteur id veniam.Quis aute nulla voluptate consequat occaecat.Velit esse do ut magna proident cillum enim enim duis non ea.Cillum adipisicing culpa adipisicing amet ut sunt adipisicing elit anim laborum sit anim aliquip nostrud.Fugiat nulla cupidatat dolor ex pariatur laborum laboris do voluptate incididunt culpa deserunt.Id dolore adipisicing nisi et aliqua adipisicing.Magna voluptate laborum ad ex voluptate.Sit ullamco occaecat occaecat qui nostrud veniam nisi excepteur proident non.Ipsum tempor incididunt ipsum ea cillum consectetur laboris labore laboris excepteur.Dolor tempor in laboris commodo ea reprehenderit magna officia ut labore amet ad.Amet ipsum laboris nisi commodo nulla deserunt ut consequat.",
		Price:       2999000,
		Category:    "Headphone",
		Image:       "18.jpg",
		Stock:       3,
	},
}
